### ISSUE TITLE
Discography/Client Listing

### ISSUE THREAD

**Issue by MikeiLL** [Storybook-Sound/website#10]
Do we want to offer a text-only view option?

artist | project | year

how would it be sorted?

Main thing is to showcase impressive/familiar artists - bragging space.

**Comment by MikeiLL** [comment]
Tweak and cleanup data.

**Comment by MikeiLL** [comment]
How to handle placeholder colors and type. Vary typefaces? Make colors consistent, for example based on project title value.

**Comment by MikeiLL** [comment]
Blank album covers is not wearing well with Scott. Text-only will also be easier to maintain.

**Comment by Rosuav** [comment]
Could be done as a quick pass over the existing content, finding the unique Artist entries. [Wouldn't be too hard](https://en.wikipedia.org/wiki/Small_matter_of_programming).

**Comment by MikeiLL** [comment]
How do we handle projects without a title?
